/*
 * SPDX-FileCopyrightText: 2025 Daisuke Nagao
 *
 * SPDX-License-Identifier: MIT
 */

#ifndef UUID_01946E67_323D_7643_BC6D_0CBFBCC20897
#define UUID_01946E67_323D_7643_BC6D_0CBFBCC20897

#include <sys/config.h>

#define TK_SUPPORT_TASKEVENT FALSE
#define TK_SUPPORT_DISWAI FALSE
#define TK_SUPPORT_IOPORT FALSE
#define TK_SUPPORT_MICROWAIT FALSE
#define TK_SUPPORT_LOWPOWER FALSE
#define TK_SUPPORT_USERBUF TRUE
#define TK_SUPPORT_AUTOBUF FALSE
#define TK_SUPPORT_MEMLIB FALSE
#define TK_SUPPORT_TASKEXCEPTION FALSE
#define TK_SUPPORT_SUBSYSTEM FALSE
#define TK_SUPPORT_SSYEVENT FALSE
#define TK_SUPPORT_SYSCONF FALSE
#define TK_HAS_DOUBLEWORD TRUE
#define TK_SUPPORT_USEC FALSE
#define TK_SUPPORT_LARGEDEV FALSE
#define TK_SUPPORT_SERCD TRUE

#define TK_SUPPORT_INTCTRL FALSE
#define TK_HAS_ENAINTLEVEL FALSE
#define TK_SUPPORT_CPUINTLEVEL FALSE
#define TK_SUPPORT_CTRLINTLEVEL FALSE
#define TK_SUPPORT_INTMODE FALSE
#define TK_SUPPORT_CACHECTRL FALSE
#define TK_SUPPORT_SETCACHEMODE FALSE
#define TK_SUPPORT_WBCACHE FALSE
#define TK_SUPPORT_WTCACHE FALSE
#define TK_SUPPORT_FPU FALSE
#define TK_SUPPORT_COP0 FALSE
#define TK_SUPPORT_COP1 FALSE
#define TK_SUPPORT_COP2 FALSE
#define TK_SUPPORT_COP3 FALSE
#define TK_SUPPORT_ASM FALSE
#define TK_SUPPORT_REGOPS FALSE
#define TK_ALLOW_MISALIGN FALSE
#define TK_BIGENDIAN FALSE
#define TK_TRAP_SVC FALSE
#define TK_HAS_SYSSTACK FALSE
#define TK_SUPPORT_PTIMER FALSE
#define TK_SUPPORT_UTC FALSE
#define TK_SUPPORT_TRONTIME FALSE
#define TK_SUPPORT_DSNAME FALSE
#define TK_SUPPORT_DBGSPT FALSE
#define TK_SPECVER_MAGIC 6
#define TK_SPECVER_MAJOR 3
#define TK_SPECVER_MINOR 0
#define TK_SPECVER ((TK_SPECVER_MAJOR * 256) | TK_SPECVER_MINOR)
#define TK_MAX_TSKPRI CFN_MAX_PRI
#define TK_WAKEUP_MAXCNT 4095
#define TK_SEMAPHORE_MAXCNT 4095
#define TK_SUSPEND_MAXCNT 4095
#define TK_MEM_RNG0 0
#define TK_MEM_RNG1 0
#define TK_MEM_RNG2 0
#define TK_MEM_RNG3 0
#define TK_MAX_PTIMER 0

#endif /* UUID_01946E67_323D_7643_BC6D_0CBFBCC20897 */
